project_id = "uynvypfkwwkoxchaghui"

[functions.check-payroll-periods]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = true

[functions.setup-company]
verify_jwt = true
